services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nykon/website-frontend:latest
    restart: always
    ports:
      - '3001:3001'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nykon/website-backend:latest
    restart: always
    ports:
      - '8080:8080'