# ============================================================================ #
#                         PNPM Workspace Configuration                         #
# ============================================================================ #
# This file defines the configuration for the pnpm workspace, which is a       #
# package management tool for JavaScript projects.                             #
#                                                                              #
# See: https://pnpm.io/settings                                                #
# ============================================================================ #

minimumReleaseAge: 0

allowBuilds:
  "esbuild": true
  "unrs-resolver": true
