import { type ComponentType } from "react";

import {
  DiscordIcon,
  DonatelloIcon,
  GitHubIcon,
  InstagramIcon,
  LinkedInIcon,
  MailIcon,
  MediumIcon,
  NPMIcon,
  PatreonIcon,
  RedditIcon,
  SpotifyIcon,
  SteamIcon,
  StreamlabsIcon,
  TelegramIcon,
  TikTokIcon,
  TwitchIcon,
  WakaTimeIcon,
  XIcon,
  YouTubeIcon,
} from "./icons";
import type { IconId, IconProps } from "./icons";

export const iconMap = new Map<IconId, ComponentType<IconProps>>([
  ["mail", MailIcon],
  ["github", GitHubIcon],
  ["telegram", TelegramIcon],
  ["youtube", YouTubeIcon],
  ["twitch", TwitchIcon],
  ["instagram", InstagramIcon],
  ["tiktok", TikTokIcon],
  ["x", XIcon],
  ["reddit", RedditIcon],
  ["linkedin", LinkedInIcon],
  ["patreon", PatreonIcon],
  ["discord", DiscordIcon],
  ["medium", MediumIcon],
  ["npm", NPMIcon],
  ["spotify", SpotifyIcon],
  ["wakatime", WakaTimeIcon],
  ["steam", SteamIcon],
  ["streamlabs", StreamlabsIcon],
  ["donatello", DonatelloIcon],
]);
